AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  coverage-reference-app
  
  Sample SAM Template for coverage-reference-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  CoveragedataFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: coveragedata/
      Handler: coveragedata
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /coveragedata
            Method: ANY
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          REDIS_URL: poc-redis-cache.apwrwg.0001.usw2.cache.amazonaws.com:6379

Outputs:
  CoveragedataAPI:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/coveragedata/"

  CoveragedataFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt CoveragedataFunction.Arn

  CoveragedataFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt CoveragedataFunctionRole.Arn
