apiVersion: apps/v1
kind: Deployment
metadata:
  name: coverage
spec:
  replicas: 3
  strategy: {}
  selector:
    matchLabels:
       app: be
       name: coverage
  template:
    metadata:
      labels:
        app: be
        name: coverage
    spec:
      containers:
      - name: coverage
        image: 742759186184.dkr.ecr.us-west-2.amazonaws.com/coverage:1.1
        env:
        - name: PU
          value: default
        - name: tra.tibco.env.CUSTOM_EXT_PREPEND_CP
          value: /opt/tibco/be/ext
        - name: KAFKA_URL
          value: a3b31d261135f11e985700abaef74a85-1432225758.us-west-2.elb.amazonaws.com:9094
        - name: CACHE_TYPE
          value: REDIS_LAMBDA
        - name: REDIS_HTTP_URL
          value: https://es0r4xjoeb.execute-api.us-west-2.amazonaws.com/Prod/coveragedata/
        - name: AWS_REGION
          value: us-west-2
        - name: REDIS_LAMBDA_ARN
          value: arn:aws:lambda:us-west-2:742759186184:function:coverage-reference-app-CoveragedataFunction-SUM238IKHALO
        - name: AS_URL
          value: http://localhost:8080
        ports:
        - containerPort: 8890
---
apiVersion: v1
kind: Service
metadata:
  name: coverage
spec:
  selector:
    app: be
    name: coverage
  ports:
  - port: 8890
  type: LoadBalancer
